---
name: Build and push container images

on:
  push:
  pull_request:
  workflow_dispatch:
  repository_dispatch:
    types: [dispatch-build]

jobs:
  make-date-tag:
    runs-on: ubuntu-latest
    outputs:
      dtag: ${{ steps.mkdatetag.outputs.dtag }}
    steps:
      - name: make date tag
        id: mkdatetag
        run: echo "::set-output name=dtag::$(date +%Y%m%d-%H%M)"

  build-image-list:
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.image-list.outputs.json }}
      custom_images: ${{ steps.image-list.outputs.custom_json }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: image-list
        run: |
          export GITHUB_EVENT_BEFORE=${{github.event.before}}
          ./build-image-list.sh

  call-workflow-build-and-push:
    uses: ./.github/workflows/build-and-push.yml
    needs: [make-date-tag, build-image-list]
    with:
      dtag: ${{ needs.make-date-tag.outputs.dtag }}
      images: ${{ needs.build-image-list.outputs.images }}
    secrets:
      OSG_HARBOR_ROBOT_USER: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
      OSG_HARBOR_ROBOT_PASSWORD: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  call-custom-workflows-build-and-push:
    uses: ./.github/workflows/build-and-push--custom.yml
    needs: [make-date-tag, build-image-list]
    with:
      dtag: ${{ needs.make-date-tag.outputs.dtag }}
      images: ${{ needs.build-image-list.outputs.custom_images }}
    secrets:
      OSG_HARBOR_ROBOT_USER: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
      OSG_HARBOR_ROBOT_PASSWORD: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

